sudo: true
dist: trusty

script:
  - ./hugo
  - echo "blog.yooxinz.com" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: public
  on:
    branch: src