sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap find hugo
  - sudo snap install hugo

script:
  - /snap/bin/hugo
  - echo "blog.yooxinz.com" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: public
  on:
    branch: src